# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minimum', '0002_delete_minimum'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('news', models.TextField(blank=True, default=None, max_length=350, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='news_picture/')),
            ],
        ),
    ]
