# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0004_auto_20171228_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picture',
        ),
    ]
