# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 14:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0005_remove_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
