# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0006_auto_20180306_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview_news',
            field=models.TextField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
