# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-07 11:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0007_news_preview_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('video', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_news',
            field=models.TextField(blank=True, default=None, max_length=220, null=True),
        ),
    ]
