# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0015_hiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiro',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='accuracy_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='accuracy_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='attack_evolution_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='attack_evolution_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='attack_radius',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='attack_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='critical_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='critical_damage_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='critical_damage_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='critical_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='critical_resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='evasion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='hp_evolution_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='hp_evolution_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='running_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='running_speed_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='running_speed_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_10',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_11',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_12',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_2',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_3',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_4',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_5',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_8',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='hiro',
            name='skill_9',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
