# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0016_auto_20180509_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiro',
            name='image_evolution',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
