# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0018_auto_20180509_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiro',
            name='image_evolution',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
