# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0021_hiro_skill_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('talent_1', models.TextField(blank=True, default=None, null=True)),
                ('talent_2', models.TextField(blank=True, default=None, null=True)),
                ('talent_3', models.TextField(blank=True, default=None, null=True)),
                ('talent_4', models.TextField(blank=True, default=None, null=True)),
                ('talent_5', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalentUpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_upp_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('talent_1', models.TextField(blank=True, default=None, null=True)),
                ('talent_2', models.TextField(blank=True, default=None, null=True)),
                ('talent_3', models.TextField(blank=True, default=None, null=True)),
                ('talent_4', models.TextField(blank=True, default=None, null=True)),
                ('talent_5', models.TextField(blank=True, default=None, null=True)),
                ('talent_6', models.TextField(blank=True, default=None, null=True)),
                ('talent_7', models.TextField(blank=True, default=None, null=True)),
                ('talent_8', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
