# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimum', '0023_auto_20180524_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalentUpp',
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='talent_8',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
