# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guild_members', '0004_guildmembers_force'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sername', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('yourself', models.TextField(blank=True, default=None, null=True)),
                ('gild_mamber', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guild_members.GuildMembers')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
