# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalroom',
            name='gild_mamber',
        ),
        migrations.RemoveField(
            model_name='personalroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonalRoom',
        ),
    ]
