# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proom', '0003_personalroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalroom',
            name='date_of_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
