# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmembers',
            name='force',
            field=models.IntegerField(default=1),
        ),
    ]
