# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild_members', '0002_auto_20171221_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildmembers',
            name='force',
        ),
    ]
